import type { Project } from "./portfolio-types";
import container from "@/assets/container-project.jpg";
import canopy from "@/assets/canopy-project.jpg";
import steel from "@/assets/steel-workshop.jpg";
import hero from "@/assets/workshop-hero.jpg";

export type { Project };

export const projects: Project[] = [
  { slug: "gerobak-kopi-kayu", name: "Gerobak Kopi Kayu + Rangka Besi", category: "Gerobak", year: "2024", materials: ["Hollow Galvanis", "Kayu Jati", "ACP Waterproof"], location: "Jepara Kota", detail: "Gerobak kopi beroda dengan meja lipat, kabinet penyimpanan, dan finishing cat duco dua warna.", image: container, ogImage: "/og/gerobak.jpg", size: "180 × 90 × 210 cm", duration: "3 minggu", finish: "Cat duco 2 warna + kayu jati natural", process: "Rangka dibuat dari hollow galvanis 4x4 cm yang dilas penuh, lalu ditutup panel kayu jati berfinishing natural. Bagian kabinet bawah diberi sekat terkunci untuk menyimpan biji kopi, cup, dan peralatan seduh, sementara meja sajian dibuat lipat agar tidak memakan tempat saat gerobak diparkir di depan ruko. Roda heavy duty 6 inci dipilih karena permukaan jalanan lokasi cukup bergelombang.", usage: "Dipakai harian untuk jualan kopi susu di depan pertokoan Jepara kota, dengan area parkir terbatas sehingga ukuran gerobak harus pas dan mudah dipindah oleh satu orang.", highlights: ["Meja sajian lipat", "Kabinet bawah terkunci", "Rak gelas & cup", "Roda heavy duty 6 inci"] },
  { slug: "gerobak-mie-ayam", name: "Gerobak Mie Ayam Modul", category: "Gerobak", year: "2024", materials: ["Hollow Galvanis", "Stainless", "Galvalum"], location: "Kalinyamatan", detail: "Gerobak angkut berpanel galvalum dengan kompor, wadah kuah, dan rak piring yang bisa dibongkar.", image: steel, ogImage: "/og/besi.jpg", size: "200 × 80 × 200 cm", duration: "2,5 minggu", finish: "Panel galvalum + stainless meja", process: "Panel galvalum dirakit sebagai badan gerobak yang ringan namun rapat air, dipadukan meja stainless untuk area kerja. Penyangga kompor dibuat ditinggikan agar api tidak langsung memanaskan badan gerobak, sedangkan wadah kuah memakai stainless food grade yang mudah dibersihkan. Rak piring dirancang bongkar-pasang supaya gerobak bisa masuk angkutan saat berpindah lokasi.", usage: "Beroperasi saat malam di kawasan Kalinyamatan dan perlu sering dibongkar untuk dibawa pulang tiap hari, jadi kepraktisan angkut menjadi pertimbangan utama.", highlights: ["Penyangga kompor tinggi", "Wadah kuah stainless", "Rak piring bongkar-pasang", "Pegangan dorong dilapisi karet"] },
  { slug: "gerobak-bakso", name: "Gerobak Bakso + Meja Servis", category: "Gerobak", year: "2023", materials: ["Steel", "Stainless", "Electrical Components"], location: "Mayong", detail: "Unit dorong beratap kanopi kecil, dilengkapi lampu LED dan tempat tabung gas di bagian bawah.", image: canopy, ogImage: "/og/kanopi.jpg", size: "190 × 95 × 215 cm", duration: "3 minggu", finish: "Cat besi anti karat", process: "Unit dorong ini memakai rangka besi yang dicat anti karat, dengan kanopi kecil melengkung sebagai pelindung dari hujan ringan. Kompartemen tabung gas ditempatkan di bagian bawah agar titik berat gerobak rendah dan tidak mudah terguling. Lampu LED 12V dipasang untuk jualan malam, menggunakan catu daya kecil yang aman dihubungkan ke aki.", usage: "Dipakai berkeliling di area Mayong, sering berhenti di lokasi tanpa penerangan sehingga lampu mandiri dan kestabilan saat didorong menjadi kebutuhan penting.", highlights: ["Kanopi kecil melengkung", "Lampu LED 12V", "Kompartemen tabung gas", "Meja servis samping"] },
  { slug: "gerobak-dimsum", name: "Gerobak Dimsum Kaca", category: "Gerobak", year: "2023", materials: ["Hollow Galvanis", "Kaca Tempered", "ACP Waterproof"], location: "Pecangaan", detail: "Gerobak display dengan etalase kaca, laci uap, dan branding yang dipasang di dua sisi.", image: hero, ogImage: "/og/booth.jpg", size: "170 × 85 × 205 cm", duration: "2 minggu", finish: "ACP putih + aksen kayu", process: "Etalase memakai kaca tempered agar tahan benturan saat perjalanan, dibingkai rangka hollow galvanis yang tidak mudah berkarat. Laci uap dibuat dari stainless dengan penutup terpisah untuk menjaga panas dimsum. Panel ACP putih di kedua sisi disiapkan sebagai bidang branding, memudahkan pemilik mengganti desain saat menu atau nama usaha berubah.", usage: "Dipakai jualan dimsum pagi hingga sore di kawasan Pecangaan, di mana tampilan display berpengaruh besar pada keputusan pembeli yang lewat.", highlights: ["Etalase kaca tempered", "Laci uap stainless", "Panel branding 2 sisi", "Lampu etalase hangat"] },
  { slug: "gerobak-sate", name: "Gerobak Sate Portable", category: "Gerobak", year: "2023", materials: ["Hollow Galvanis", "Besi Beton", "Kayu Jati"], location: "Bangsri", detail: "Gerobak lipat untuk pasar malam dengan panggangan terbuka dan penyangga yang bisa diturunkan.", image: steel, ogImage: "/og/besi.jpg", size: "160 × 75 × 195 cm", duration: "2 minggu", finish: "Kayu jati + rangka dicat", process: "Gerobak ini memakai sistem lipat: meja dan penyangga bisa diturunkan sehingga dimensinya menyusut saat diangkut. Panggangan dibuat terbuka agar asap tidak menumpuk, dan bagian kayu jati dipilih untuk area yang bersentuhan dengan panas karena lebih stabil dibanding kayu lunak.", usage: "Digunakan untuk berjualan di pasar malam Bangsri yang lokasinya berpindah, sehingga kecepatan bongkar-pasang lebih penting daripada luas area kerja.", highlights: ["Sistem lipat ringkas", "Panggangan terbuka", "Penyangga turun", "Rak bumbu gantung"] },
  { slug: "gerobak-es-teh", name: "Gerobak Es Teh Keliling", category: "Gerobak", year: "2022", materials: ["Hollow Galvanis", "Galvalum", "Aluminium"], location: "Jepara Kota", detail: "Unit ringan dengan dua roda besar, wadah es berinsulasi, dan panel branding cetak.", image: container, ogImage: "/og/gerobak.jpg", size: "140 × 70 × 180 cm", duration: "2 minggu", finish: "Panel aluminium + stiker branding", process: "Bobot gerobak dijaga seringan mungkin dengan panel aluminium dan rangka hollow galvanis berukuran kecil. Wadah es dibuat berinsulasi agar tidak cepat mencair pada siang hari, dan roda besar 8 inci membantu melewati jalan berbatu. Gelas digantung pada rel di sisi gerobak untuk menghemat ruang meja.", usage: "Dipakai keliling Jepara kota sepanjang hari, sehingga berat total dan kenyamanan dorong menjadi dua faktor yang paling menentukan.", highlights: ["Bobot ringan", "Wadah es berinsulasi", "Roda besar 8 inci", "Gelas gantung"] },
  { slug: "gerobak-nasi-goreng", name: "Gerobak Nasi Goreng Set", category: "Gerobak", year: "2022", materials: ["Steel", "Stainless", "Electrical Components"], location: "Mlonggo", detail: "Set gerobak dengan tungku angin, meja potong, dan rak bumbu yang disusun sesuai alur masak.", image: canopy, ogImage: "/og/kanopi.jpg", size: "175 × 90 × 200 cm", duration: "2,5 minggu", finish: "Cat besi + meja stainless", process: "Tata letak disusun mengikuti alur masak: bahan mentah di satu sisi, meja potong di tengah, dan panggangan di sisi lain agar pergerakan penjual tidak bolak-balik. Tungku angin dipakai supaya panas lebih terkendali dan hemat bahan bakar. Rak bumbu dibuat bertingkat supaya semua wadah terjangkau tanpa menumpuk di meja.", usage: "Beroperasi malam di kawasan Mlonggo dengan alur pesanan cepat; susunan alat yang efisien memangkas waktu tunggu pembeli.", highlights: ["Tungku angin", "Meja potong lebar", "Rak bumbu bertingkat", "Stop kontak & lampu"] },
  { slug: "booth-kopi-susu", name: "Booth Kopi Susu Kontainer", category: "Booth", year: "2024", materials: ["ACP Waterproof", "Steel", "Electrical Components"], location: "Jepara", detail: "Booth kontainer berukuran compact dengan jendela servis geser dan area penyimpanan belakang.", image: hero, ogImage: "/og/booth.jpg", size: "220 × 150 × 250 cm", duration: "4 minggu", finish: "ACP + cat duco", process: "Booth memakai panel ACP waterproof supaya aman terkena hujan dan mudah dibersihkan. Jendela servis dibuat geser, bukan buka-tutup, agar tidak menghalangi area jalan di depannya. Bagian belakang difungsikan sebagai gudang penyimpanan bahan dan peralatan cadangan, dengan instalasi listrik yang sudah disiapkan untuk mesin kopi dan lampu.", usage: "Berada di lokasi tetap selama jam operasional, jadi unsur utamanya adalah ketahanan cuaca dan alur pelayanan yang lancar saat ramai.", highlights: ["Jendela servis geser", "Gudang belakang", "Instalasi listrik", "Meja bar kayu"] },
  { slug: "kanopi-gerobak-teras", name: "Kanopi Gerobak & Teras Usaha", category: "Kanopi", year: "2023", materials: ["Galvalum", "Hollow Galvanis", "ACP Waterproof"], location: "Jepara", detail: "Kanopi melengkung untuk area gerobak usaha, dirancang menahan hujan deras dan mudah dibersihkan.", image: canopy, ogImage: "/og/kanopi.jpg", size: "400 × 250 cm", duration: "1,5 minggu", finish: "Atap galvalum + talang", process: "Kanopi dibuat melengkung agar air hujan tidak menggenang, dengan talang yang mengarahkan air ke satu titik pembuangan. Rangka hollow galvanis dipilih karena tahan karat di area terbuka, sedangkan atap galvalum memberi bobot ringan sehingga tidak membebani struktur penyangga yang sudah ada. Titik lampu disiapkan di beberapa posisi untuk penerangan malam.", usage: "Menutupi area gerobak dan teras usaha yang dipakai dari pagi sampai malam, sehingga fungsi utamanya adalah melindungi dari hujan sekaligus menjaga area tetap terang.", highlights: ["Bentuk melengkung", "Talang air", "Rangka hollow galvanis", "Titik lampu"] },
  { slug: "gerbang-bengkel", name: "Gerbang & Rangka Besi Bengkel", category: "Besi", year: "2022", materials: ["Steel", "Hollow Galvanis"], location: "Kalinyamatan", detail: "Gerbang geser dan rangka portal untuk bengkel usaha dengan perhitungan bukaan lebar.", image: steel, ogImage: "/og/besi.jpg", size: "Lebar bukaan 500 cm", duration: "3 minggu", finish: "Cat besi anti karat", process: "Gerbang dibuat geser untuk menghemat ruang bukaan di depan bengkel, dengan roda rel heavy duty yang sanggup menahan beban panel. Rangka portal dihitung terhadap lebar bukaan agar tidak melentur saat daun gerbang dibuka penuh. Seluruh sambungan dilas penuh lalu dicat anti karat, termasuk bagian dalam rangka yang sulit dijangkau.", usage: "Dipakai sebagai akses kendaraan keluar-masuk bengkel di Kalinyamatan yang frekuensinya tinggi, sehingga kekuatan rel dan ketahanan cat menjadi prioritas.", highlights: ["Gerbang geser rel", "Rangka portal", "Roda rel heavy duty", "Panel isi hollow"] },
];

export const categories = ["Semua", "Gerobak", "Booth", "Kanopi", "Besi"] as const;

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}

export function getNeighbors(slug: string) {
  const index = projects.findIndex((project) => project.slug === slug);
  if (index === -1) return { prev: undefined, next: undefined };
  return {
    prev: index > 0 ? projects[index - 1] : projects[projects.length - 1],
    next: index < projects.length - 1 ? projects[index + 1] : projects[0],
  };
}
